fix(interceptor): not error on cleared handler after delay (#1165)
### Fixes

- Calling `handler.clear()` or `interceptor.clear()` while awaiting a
response delay cause the error `TypeError:
this.createResponseDeclaration is not a function`. The method
`HttpRequestHandlerClient#applyResponseDeclaration` should return
undefined if the response declaration is cleared before the response is
sent.